[package]
name = "rapl-energy"
version = "0.1.9"
edition = "2021"
categories = ["development-tools::profiling"]
keywords = ["benchmarking", "energy", "sustainability"]
description = "Small library for getting the CPU energy consumption from RAPL"
repository = "https://github.com/JordyAaldering/rapl-energy"
license = "Apache-2.0"
readme = "README.md"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[features]
default = ["http"]
http = ["dep:ureq"]

[dependencies]
indexmap = "2.2.6"
ureq = { version = "2.10.0", optional = true }

[build-dependencies]
cbindgen = "0.26.0"
