[package]
name = "rapl-energy"
version = "0.1.13"
edition = "2021"
categories = ["development-tools::profiling"]
keywords = ["benchmarking", "energy", "sustainability"]
description = "Small library for getting the CPU energy consumption from RAPL"
repository = "https://github.com/JordyAaldering/rapl-energy"
license = "Apache-2.0"
readme = "README.md"

[lib]
crate-type = ["lib", "cdylib"]

[features]
default = ["http"]
http = ["dep:ureq"]
hwmon = ["dep:libmedium"]
nvml = ["dep:nvml-wrapper", "dep:once_cell"]

[dependencies]
indexmap = "2.2.6"
libmedium = { version = "0.11.0", optional = true }
nvml-wrapper = { version = "0.10.0", optional = true }
once_cell = { version = "1.19.0", optional = true }
ureq = { version = "2.10.0", optional = true }

[build-dependencies]
cbindgen = "0.26.0"
