[package]
name = "rapl-energy"
version = "0.2.2"
edition = "2024"
categories = ["development-tools::profiling"]
keywords = ["benchmarking", "energy", "sustainability"]
description = "Small library for getting the CPU energy consumption from RAPL"
repository = "https://github.com/JordyAaldering/rapl-energy"
license = "GPL-3.0"
readme = "README.md"

[lib]
crate-type = ["lib", "cdylib"]

[features]
libc = ["cbindgen"]

[dependencies]
indexmap = "2.14.0"

[build-dependencies]
cbindgen = { version = "0.29.3", optional = true }
