[package]
name = "rapl-energy-c"
edition = "2021"

[lib]
name = "rapl_energy_c"
path = "libc.rs"
crate-type = ["staticlib"]

[dependencies]
rapl-energy = { path = "../rapl-energy" }
serde_json = "1.0.120"
