name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - uses: actions/upload-artifact@v4
      with:
        name: rapl_energy.h
        path: target/rapl_energy.h
    - uses: actions/upload-artifact@v4
      with:
        name: librapl_energy.a
        path: target/release/librapl_energy.a
    - uses: actions/upload-artifact@v4
      with:
        name: librapl_energy.so
        path: target/release/librapl_energy.so
